### PR TITLE
Fetch Missing Samples and Sort by Library

### LINKED ISSUE #131: Investigate on missing samples from dashboard
**Describe the bug**
Investigate on why some samples are missing from the dashboard

### PR DESCRIPTION
**Pull request by MaggieKimani1**
## Description

- Adds all the missing samples and filters out the localized ones to be displayed on the dashboard.
- Also adds a filtering tool for one to search by library name
- Sorts the libraries in the details page alphabetically
### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Filter and Sort

image

### Missing Java sdks
image

#### Closing issue
Fixes #131, #141

### CODE REVIEW

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx [hunk 1]
```diff
@@ -88,27 +92,35 @@ export default class Details extends React.Component<any, any> {
...
-                url: data.url
-            },
+            name: repositoryName,
+            description: data.description,
+            url: data.url
+        },
+
             isLoading: false
-        });
+        });
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx:104]: format the files so it cleans up things like these whitespaces.

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx [hunk 2]
```diff
@@ -88,27 +92,35 @@ export default class Details extends React.Component<any, any> {
...
+        
+        if (items.length === 0) {
+            return null;
+        }
         for (const item of items) {
-
             switch (item.status) {
-                case 1:
+                case 0:
+                    unknownCount = unknownCount + 1;
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx:121]:
```suggestion
                    unknownCount++;
```

File: SamplesDashboard/SamplesDashboard/Services/AzureSdkService.cs [hunk 3]
```diff
@@ -82,13 +82,17 @@ public async Task<string> GetAzureSdkVersions(string packageName)
...
-            foreach (var sdk in sdks)
+            if (sdks != null)
             {
-                if (sdk.Key == packageName)
+                foreach (var sdk in sdks)
                 {
-                    azureSdkVersion = sdk.Value;
+                    if (sdk.Key == packageName)
+                    {
+                        azureSdkVersion = sdk.Value;
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Services/AzureSdkService.cs:91]: i assume you want to break the loop if you found it.

File: SamplesDashboard/SamplesDashboard/Services/AzureSdkService.cs [hunk 4]
```diff
@@ -82,13 +82,17 @@ public async Task<string> GetAzureSdkVersions(string packageName)
             string azureSdkVersion = String.Empty;
 
             var sdks = await FetchAzureSdkVersions();
-            foreach (var sdk in sdks)
+            if (sdks != null)
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Services/AzureSdkService.cs:85]: you can reduce the nesting by saying 

if (sdks == null){
return String.Empty
}

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx [hunk 5]
```diff
@@ -143,21 +142,23 @@ IRepositoryState> {
...
-                        uptoDateCount = uptoDateCount + 1;
-                        break;
-                    case 2:
-                        majorUpdateCount = majorUpdateCount + 1;
-                        break;
-                    case 3:
-                        patchUpdateCount = patchUpdateCount + 1;
-                        break;
+            if (item.vulnerabilityAlerts !== null) {
+                if (item.vulnerabilityAlerts.totalCount > 0) {
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx:146]: combine these if statements.

if item.vulnerabilityAlerts && item.vulnerabiltyAlerts.totalCount > 0

File: SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs [hunk 6]
```diff
@@ -140,22 +140,31 @@ public async Task<List<Node>> GetRepositories(string name, string endCursor = nu
             if (hasNextPage == true)
             {
                 var nextRepos = await GetRepositories(name, endCursor);
-                repos.AddRange(nextRepos);
-            }       
+                repositories.AddRange(nextRepos);
+            }
 
-            return repos;            
+            //remove localized repos
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs:146]: add a reason localized repos are removed

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx [hunk 7]
```diff
@@ -88,27 +92,35 @@ export default class Details extends React.Component<any, any> {
         // call the statistics function
         this.statusStatistics(this.allItems);
         this.setState({
-            items: this.allItems,
+            items: this.allItems.sort((a, b) => (a.packageName.toLowerCase() >
+                b.packageName.toLowerCase()) ? 1 : -1),
```
Comment (thewahome) [inline SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx:96]: The sorting function can be abstracted so that it is easily readable and reusable. So that now items looks like
`items: sortItems(allItems, packageName.toLowercase, 'DESC)`,

Comment (MaggieKimani1) [reply SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx:96]: Oh yes, good catch!

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx [hunk 8]
```diff
@@ -92,18 +92,20 @@ export default class Details extends React.Component<any, any> {
...
+                url: data.url
+            },
             isLoading: false
         });
     }
 
+    public sortItems(items: IDetailsItem[]) {
+        const sortedItems = items.sort((a, b) => (a.packageName.toLowerCase() > b.packageName.toLowerCase()) ? 1 : -1);
+        return sortedItems;
+    }
```
Comment (thewahome) [inline SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx:108]: It should look like this

```suggestion
    public sortItems(items: IDetailsItem[], property) {
        const sortColumn = property.toLowerCase();
        const sortedItems = items.sort((a, b) => (a[sortColumn] > b[sortColumn]) ? 1 : -1);
        return sortedItems;
    }
```
So that you can call it like so

`sortItems(allItems, packageName)`
Then put it in a separate utility file so that it can be used in other places where sorting is required

However this does not need to be fixed in this PR

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx [hunk 9]
```diff
@@ -143,21 +142,22 @@ IRepositoryState> {
...
         for (const item of items) {
-            if (item.vulnerabilityAlerts.totalCount > 0) {
-                urgentUpdateCount = urgentUpdateCount + 1;
-            } else {
+            if (item.vulnerabilityAlerts && item.vulnerabilityAlerts && item.vulnerabilityAlerts.totalCount > 0) {
+                urgentUpdateCount++;
+            }
+            else {
                 switch (item.repositoryStatus) {
                     case 1:
```
Comment (thewahome) [inline SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx:150]: It is not clear what the case 1/2/3 values are. This can change to an enum so that it is clear what the cases are checking for

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx [hunk 10]
```diff
@@ -366,7 +366,10 @@ function renderItemColumn(item: IRepositoryItem, index: number | undefined, colu
     const views = item.views;
     const url = item.url;
     const featureArea = item.featureArea;
-    const vulnerabilityAlertsCount = item.vulnerabilityAlerts.totalCount;  
+    if (item.vulnerabilityAlerts === null) {
+        return null;
+    }
```
Comment (thewahome) [inline SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx:371]: [nit pick] Typescript helps us do the null checks in an easier way, So that the `==null` check is not required

```suggestion
    if (!item.vulnerabilityAlerts) {
        return null;
    }
```

File: SamplesDashboard/SamplesDashboard/Services/AzureSdkService.cs [hunk 11]
```diff
@@ -82,6 +82,10 @@ public async Task<string> GetAzureSdkVersions(string packageName)
             string azureSdkVersion = String.Empty;
 
             var sdks = await FetchAzureSdkVersions();
+            if (sdks == null)
+            {
+                return  String.Empty;  
+            }
```
Comment (thewahome) [inline SamplesDashboard/SamplesDashboard/Services/AzureSdkService.cs:88]: the null check can be changed here as well

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx [hunk 12]
```diff
@@ -88,48 +92,56 @@ export default class Details extends React.Component<any, any> {
...
+    // compute status statistics
     public statusStatistics(items: IDetailsItem[]) {
         let uptoDateCount = 0;
         let urgentUpdateCount = 0;
         let majorUpdateCount = 0;
         let patchUpdateCount = 0;
         let unknownCount = 0;
```
Comment (thewahome) [inline SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx:115]: A type can be created to help define what goes in to the statistics like
`export interface IUpdateStats {
  count: number;
  percent: number;
  total: number;
}`

So that we can then use it like so
```suggestion
  let uptoDate :IUpdateStats = {
    count: 0,
    percent: 0,
    total: 0
  }
  let urgentUpdate :IUpdateStats = {
    count: 0,
    percent: 0,
    total: 0,
  }
  let majorUpdate :IUpdateStats = {
    count: 0,
    percent: 0,
    total: 0,
  }
  let patchUpdate :IUpdateStats = {
    count: 0,
    percent: 0,
    total: 0
  }
  let unknown :IUpdateStats = {
    count: 0,
    percent: 0,
    total: 0
  }
```

Thus we eliminate the need to have related variables that are getting declared separately

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx (hunk 9 above)
Comment (MaggieKimani1) [reply SamplesDashboard/SamplesDashboard/ClientApp/src/views/repositories/Repositories.tsx:150]: We store the status values as an enum in the backend, then we send them to the front end.

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx (hunk 8 above)
Comment (MaggieKimani1) [reply SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx:108]: So I'll need to create a separate branch to move the code into a utility file?

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx [hunk 13]
```diff
@@ -88,48 +94,52 @@ export default class Details extends React.Component<any, any> {
...
         this.statusStatistics(this.allItems);
         this.setState({
-            items: this.allItems,
+            items: copyAndSort(this.allItems, 'packageName'),
             repositoryDetails: {
-                name: repositoryName,
-                description: data.description,
+            name: repositoryName,
+            description: data.description,
                 url: data.url
```
Comment (andrueastman) [inline SamplesDashboard/SamplesDashboard/ClientApp/src/views/details/Details.tsx:101]: Nitpick . The indentation here is inconsitent

File: SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs [hunk 14]
```diff
@@ -140,22 +140,31 @@ public async Task<List<Node>> GetRepositories(string name, string endCursor = nu
...
             {
                 var nextRepos = await GetRepositories(name, endCursor);
-                repos.AddRange(nextRepos);
-            }       
+                repositories.AddRange(nextRepos);
+            }
 
-            return repos;            
+            //remove localized repos to reduce repetition of samples
+            foreach (var repo in repositories.ToList())
```
Comment (andrueastman) [inline SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs:147]: I think the better way of filtering out the localized repos would be use Regex to filter out names ending with the pattern `.xx-XX`.
This way we are sure the repo is a localization.
