### PR TITLE
FHL Hack on dashboard

### LINKED ISSUE #145: Non-owner is shown as an owner
**Describe the bug**
It appears that the top three contributors are shown as the SDK owner. One of the three for PHP is not an owner.  Who is an owner? I think anyone with the Admin or Maintain perm could be considered an owner, although we'd have to be comfortable with a GH team as an owner. We could filter non-members of the org from the "owner" list. 

**To Reproduce**
image

**Expected behavior**
Only members of the microsoftgraph GH organization are shown in owners field. 
[AB#8350](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8350)

### PR DESCRIPTION
**Pull request by jasonjoh**
Made numerous changes and improvements.

- Owners field is now pulled from GitHub Management Portal for Open Source instead of guessed at from GitHub collaborators. (Note this requires onboarding of production app ID before it will work)
- Implemented basic dependency graph support for Gradle-based Java projects. GitHub does not support Gradle when it builds it's graph.
- Implemented Maven service to look up latest versions of Java dependencies (to support the Gradle graph support).
- Separated minor and major updates into their own statuses, added additional card to repo list to show their percentages
- Identity library and Graph SDK updates statuses are called out in the repo list
- Adjusted repo filters to remove private repos from the list
- Refactored to remove tutorial localization repos from the list *before* querying GitHub for their stats.
- Added a "Last updated" column in the repo list
- List is sorted alphabetically by default
- Added an alternative to the YAML header in the README. Repos can opt to add a dev.yml file in the root and add the relevant info there.
- Adjusted how percentages on repo list page are calculated. Repos with a status of "unknown" are removed from the total before calculating percentage.

## Description

Please include a summary of the change.

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Testing
Please describe the tests that you ran to verify your changes.

#### Closing issue
Fixes #145

### CODE REVIEW

**Comment by jasonjoh** [comment]
These tests are failing currently because testing needs access to app ID and secret due to new service that queries Microsoft maintainers. Not sure how to give the test project access to that data. Locally I was adding it to the appsettings.json in the test project.

Once that's resolved though, the app ID needs to be onboarded to the internal API that queries maintainers.

**Comment by andrueastman** [comment]
@jasonjoh Any chance you could provide links to the api documentation about the GitHub Management Portal for Open Source apis so that we can create the necessary credentials for the app to use?

**Comment by jasonjoh** [comment]
@andrueastman there aren't any docs that I'm aware of. I reached out to the folks that run the portal and they provided me with the API. I had to give them my app ID so they could add it to their allow list. I'll add you to the email thread.

**Review by MaggieKimani1 — COMMENTED** [review]
This is such great work!
Thank you for picking it up during FHL and doing some fixes and adding features to it as well.😊
Would you mind adding me to the email thread as well?

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/Home.tsx [hunk 1]
```diff
@@ -30,7 +30,7 @@ export default class Home extends React.Component<any> {
                         <Repositories isAuthenticated={true} title={'samples'} />
                     </div>
                 </PivotItem>
-                <PivotItem headerText='Code Projects'>
+                <PivotItem headerText='SDKs'>
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/ClientApp/src/views/Home.tsx:33]: changed this name a while back because the projects being tracked aren't just SDKs.

File: SamplesDashboard/SamplesDashboard/Models/MavenQuery.cs [hunk 2]
```diff
@@ -0,0 +1,26 @@
+// ------------------------------------------------------------------------------
+//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
+// ------------------------------------------------------------------------------
+
+using System.Collections.Generic;
+using Newtonsoft.Json;
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Models/MavenQuery.cs:6]:
```suggestion
```

File: SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs [hunk 3]
```diff
@@ -158,7 +171,14 @@ public class Repository
         [JsonProperty("dependencyGraphManifests")]
         public DependencyGraphManifests DependencyGraphManifests { get; set; }
 
+        [JsonProperty("defaultBranchRef")]
+        public Branch DefaultBranch { get; set; }
+
         public PackageStatus highestStatus { get; set; }
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs:177]: naming style is inconsistent

File: SamplesDashboard/SamplesDashboard/Services/MavenService.cs [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+namespace SamplesDashboard.Services
+{
+    /// <summary>
+    /// This class contains search.maven.org queries to be used by the samples
+    /// </summary>
+    public class MavenService
+    {
+        private readonly IHttpClientFactory _clientFactory;
+        private readonly IConfiguration _config;
+        private IMemoryCache _cache;
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Services/MavenService.cs:23]:
```suggestion
        private readonly IMemoryCache _cache;
```

File: SamplesDashboard/SamplesDashboard/Services/MavenService.cs [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+
+        /// <summary>
+        ///Creates a httpclient to query Maven's registry to get package details
+        /// </summary>
+        /// <param name="packageName"></param>
+        /// <returns>latest package version</returns>
+        public async Task<string> GetLatestVersion(string packageName)
+        {
+            MavenQuery mavenData;
+            if (!_cache.TryGetValue($"maven: {packageName}", out mavenData))
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Services/MavenService.cs:40]:
```suggestion
            if (!_cache.TryGetValue($"maven: {packageName}", out MavenQuery mavenData))
```

File: SamplesDashboard/SamplesDashboard/Services/MavenService.cs [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+            {
+                var httpClient = _clientFactory.CreateClient();
+
+                var packageParts = packageName.Split(':');
+                var apiUrl = $"https://search.maven.org/solrsearch/select?q=g:%22{packageParts[0]}%22%20AND%20a:%22{packageParts[1]}%22&rows=1&wt=json";
+                HttpResponseMessage responseMessage = await httpClient.GetAsync(apiUrl);
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Services/MavenService.cs:46]:
```suggestion
                var responseMessage = await httpClient.GetAsync(apiUrl);
```

File: SamplesDashboard/SamplesDashboard/Services/MavenService.cs [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+
+                if (responseMessage.IsSuccessStatusCode)
+                {
+
+                    using (var stream = await responseMessage.Content.ReadAsStreamAsync())
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Services/MavenService.cs:51]:
```suggestion
                    await using var stream = await responseMessage.Content.ReadAsStreamAsync();
```

File: SamplesDashboard/SamplesDashboard/Services/MavenService.cs [hunk 8]
```diff
@@ -0,0 +1,73 @@
...
+
+                        var cacheEntryOptions = new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromSeconds(_config.GetValue<double>(Constants.Timeout)));
+                        _cache.Set($"maven: {packageName}", mavenData, cacheEntryOptions);
+                    }
+                }
+            }
+
+            if (mavenData?.Response?.NumFound > 0)
+            {
+                return mavenData?.Response?.Docs[0]?.LatestVersion;
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Services/MavenService.cs:67]:
```suggestion
                return mavenData?.Response?.NumFound > 0 ? mavenData.Response?.Docs[0]?.LatestVersion : "";
```

File: SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+    /// This class contains query services for the Microsoft Open Source GitHub portal
+    /// </summary>
+    public class MicrosoftOpenSourceService
+    {
+        private readonly IHttpClientFactory _clientFactory;
+        private readonly IConfiguration _config;
+        private readonly ILogger<MicrosoftOpenSourceService> _logger;
+        private readonly IConfidentialClientApplication _cca;
+        private static readonly string[] _scopes =
+            { "api://5bc5e692-fe67-4053-8d49-9e2863718bfb/.default" };
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs:26]: anything special to know about this guid?  what does it represent.

File: SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs [hunk 10]
```diff
@@ -0,0 +1,86 @@
...
+            try
+            {
+                var tokenResponse = await _cca
+                .AcquireTokenForClient(_scopes)
+                .ExecuteAsync();
+
+                var client = _clientFactory.CreateClient();
+
+                var apiPath =
+                    $"https://repos.opensource.microsoft.com/api/maintainers/org/{organization}/repo/{repoName}?api-version=2017-09-01";
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs:61]: anything special about this variable.  should it be a constant so the meaning is clear.

File: SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs [hunk 11]
```diff
@@ -0,0 +1,86 @@
...
+                var request = new HttpRequestMessage(HttpMethod.Get, apiPath);
+                request.Headers.Authorization =
+                    new AuthenticationHeaderValue("Bearer", tokenResponse.AccessToken);
```
Comment (ddyett) [inline SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs:64]: doesn't this need validation in case we didn't get a token?

Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs:64]: I suspect that any case where `tokenResponse` is null would throw an `MsalException`, but it's probably best not to assume that's always true.

File: SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs (hunk 3 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs:177]: True, but that was pre-existing :D. Did you want me to fix all of the property names to Pascal case (like the majority of properties in that file), or should that be a separate code-cleanup PR?

File: SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs (hunk 9 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs:26]: It's the app ID of the internal API. I'll add it as a constant and build the string from it.

Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs:26]: Or no, I'll just comment the `_scopes` property.

File: SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs (hunk 10 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs:61]: It's the REST API endpoint. It can't be constant since it's built using parameters. To make it constant I'd need to do something like:

```
const string apiPath = "https://repos.opensource.microsoft.com/api/maintainers/org/{0}/repo/{1}?api-version=2017-09-01";
var request = new HttpRequestMessage(HttpMethod.Get, string.Format(api, organization, repoName));
```

File: SamplesDashboard/SamplesDashboard/ClientApp/src/views/Home.tsx (hunk 1 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/ClientApp/src/views/Home.tsx:33]: Oh I see. The production one still says SDK's, that's why I changed it. Are you saying that you didn't like "Code Projects" either? Should we come up with a satisfactory name? Maybe "Tools & SDKs"?

File: SamplesDashboard/SamplesDashboard/Models/MavenQuery.cs (hunk 2 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Models/MavenQuery.cs]: Fixed in latest push.

File: SamplesDashboard/SamplesDashboard/Services/MavenService.cs (hunk 4 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Services/MavenService.cs]: Fixed in latest push

File: SamplesDashboard/SamplesDashboard/Services/MavenService.cs (hunk 5 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Services/MavenService.cs]: Fixed in latest push

File: SamplesDashboard/SamplesDashboard/Services/MavenService.cs (hunk 6 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Services/MavenService.cs]: Fixed in latest push

File: SamplesDashboard/SamplesDashboard/Services/MavenService.cs (hunk 7 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Services/MavenService.cs]: Fixed in latest push

File: SamplesDashboard/SamplesDashboard/Services/MavenService.cs (hunk 8 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Services/MavenService.cs]: Fixed in latest push

File: SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs (hunk 9 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs:29]: Fixed in latest push, I'll leave it to you to resolve if you agree with my fix :D.

File: SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs (hunk 11 above)
Comment (jasonjoh) [reply SamplesDashboard/SamplesDashboard/Services/MicrosoftOpenSourceService.cs:72]: Fixed in latest push, I'll leave it to you to resolve if you agree with my fix :D.

File: SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs (hunk 3 above)
Comment (andrueastman) [reply SamplesDashboard/SamplesDashboard/Models/SampleQueries.cs:177]: We can address this in a separate PR :)

**Comment by andrueastman** [comment]
@jasonjoh The validation/deployment pipelines have now been updated/fixed pipelines to cater for the updates proposed and you can checkout this work on the dev environment at this link. https://devxdashboard-dev.azurewebsites.net/

Please let me know if everything works as intended then we can move on to push this to production.

**Comment by jasonjoh** [comment]
Looks good @andrueastman. 

Just as FYI I've got some additional changes I'm working on but those won't be ready for a few days at least.

**Comment by andrueastman** [comment]
No worries about that. 
We are looking forward to the changes and thanks for making time to contribute!
