### PR TITLE
Fix urgent update and Status sorting issue

### LINKED ISSUE #128: Sorting by status doesn't work properly
**Describe the bug**
Sorting by the **Status** column doesn't work as expected. Items seem to be randomly placed.

**To Reproduce**
1. Go to dashboard
1. Click the **Status** column

**Expected behavior**
The list is sorted, with all items of a certain status together

**Screenshots**

image

**Additional context**

It would be super helpful to be able to quickly see all the samples that have urgent updates. Sorting like this would do that.

### PR DESCRIPTION
**Pull request by MaggieKimani1**
## Description

Change computation for an urgent update status to represent specific libraries with security alerts
### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshot
image

Sorting
image

#### Closing issue
Fixes #128 , #135

### CODE REVIEW

File: SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs [hunk 1]
```diff
@@ -320,7 +333,26 @@ internal async Task<Repository> UpdateRepositoryStatus(Repository repository)
 
                     dependency.latestVersion = latestVersion;
                     dependency.azureSdkVersion = azureSdkVersion;
-                    dependency.status = CalculateStatus(currentVersion.Substring(2), latestVersion);
+
+                    //calculate status normally for repos without security alerts
+                    if (vulnerabilityCount == 0)
```
Comment (andrueastman) [inline SamplesDashboard/SamplesDashboard/Services/RepositoriesService.cs:338]: Nit: surround if block with curly braces
